### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by naomipol** [ludohenin/gulp-inline-ng2-styles#3]
I'm trying to use this package to inline my `scss` files into angular2 components.

My gulpfile:
```
gulp.task('js:build', function () {
    gulp.src('src/**/*.ts')
        .pipe(embedTemplates({ sourceType: 'ts'}))
        .pipe(inlineNg2Styles({ base: '/dist/styles', extension: '.scss' }))
        .pipe(gulp.dest('./dist'));
});
```

But when running I get a `SyntaxError: Unexpected token export` exception.

stack trace:
```
SyntaxError: Unexpected token export
    at replace (...\node_modules\gulp-inline-ng2-styles\index.js:88:36)
    at ...\node_modules\gulp-inline-ng2-styles\index.js:74:44
    at Array.forEach (native)
    at inline (...\node_modules\gulp-inline-ng2-styles\index.js:50:9)
    at DestroyableTransform._transform (...\node_modules\gulp-inline-ng2-styles\index.js:30:34)
    at DestroyableTransform.Transform._read (...\node_modules\gulp-inline-ng2-styles\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (...\node_modules\gulp-inline-ng2-styles\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (...\node_modules\gulp-inline-ng2-styles\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (...\node_modules\gulp-inline-ng2-styles\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (...\node_modules\gulp-inline-ng2-styles\node_modules\readable-stream\lib\_stream_writable.js:274:11)
```

**Comment by phip1611** [comment]
I'm experiencing the same error. Please fix.
